name: CatapultBlocks
main: catapultblocks.CatapultBlocks
version: 1.0
commands:
    catapultblock:
        aliases: [cblock, cb]
        usage: /cb <north|east|south|west|up> <velX> <velY> <velZ>
        
    catapultblockhelp:
        aliases: [cblockhelp, cbhelp]
        usage: /cbhelp 