name: PuzzlePack
main: puzzlepack.PuzzlePack
version: 1.0
depend: [WorldEdit]
commands:
    secretarea:
            aliases: [secarea, sarea]
            
    secretarealist:
            aliases: [secarealist, secareal, sarealist, sareal]
            
    secretareadelete:
            aliases: [secareadelete, secareadel, secaread, sareadelete, sareadel, saread]
            
    secretareaselection:
            aliases: [secareaselection, secareasel, secareas, sareaselection, sareasel, sareas]
            
    teleportarea:
            aliases: [tparea]
            
    teleportarealist:
            aliases: [tparealist, tpareal]
    
    teleportareadelete:
            aliases: [tpareadelete, tpareadel, tparead]
    
    teleportareaselection:
            aliases: [tpareaselection, tpareasel, tpareas]
    
    clearinvarea:
            aliases: [cinarea]
            
    clearinvarealist:
            aliases: [cinarealist, cinareal]
    
    clearinvareadelete:
            aliases: [cinareadelete, cinareadel, cinaread]
    
    clearinvareaselection:
            aliases: [cinareaselection, cinareasel, cinareas]
            
    bounceblock:
            aliases: [bblock]
            
