name: ToggleBlocks
main: toggleblocks.ToggleBlocks
version: 1.0
commands:
    toggleblocks:
        aliases: [tb]
        usage: /toggleblocks <name>
        
    toggleblockson:
        aliases: [tbon]
        usage: /toggleblockson <name>
        
    toggleblocksoff:
        aliases: [tboff]
        usage: /toggleblocksoff <name>
        
    toggleblocksedit:
        aliases: [tbedit]
        usage: /toggleblocksedit <name>
        
    toggleblockslink:
        aliases: [tblink]
        usage: /toggleblockslink <name>
        
    toggleblocksrlink:
        aliases: [tbrlink]
        usage: /toggleblocksrlink <name>
        
    toggleblocksdelink:
        aliases: [tbdelink]
        usage: /toggleblocksdelink <name>
        
    toggleblockslist:
        aliases: [tblist]
        usage: /toggleblockslist
        
    toggleblocksdelete:
        aliases: [tbdelete, tbdel]
        usage: /toggleblocksdelete <name>