name: ToggleBlocks
main: toggleblocks.ToggleBlocks
version: 1.0
depend: [PuzzlePack]
commands:
    toggleblocks:
        aliases: [tb]
        usage: /tb <name>
        
    toggleblockson:
        aliases: [tbon]
        usage: /tbon <name>
        
    toggleblocksoff:
        aliases: [tboff]
        usage: /tboff <name>
                
    toggleblockslink:
        aliases: [tblink]
        usage: /tblink <name>
        
    toggleblocksrlink:
        aliases: [tbrlink]
        usage: /tbrlink <name>
        
    toggleblocksdelink:
        aliases: [tbdelink]
        usage: /tbdelink <name>
        
    toggleblockslist:
        aliases: [tblist]
        usage: /tblist
        
    toggleblocksdelete:
        aliases: [tbdelete, tbdel]
        usage: /tbdelete <name>
        
    toggleblockshelp:
        aliases: [tbhelp]
        usage: /tbhelp