name: ToggleBlocks
main: toggleblocks.ToggleBlocks
version: 1.0
depend: [PuzzlePack]
commands:
    toggleblocks:
        aliases: [tb]
        usage: /tb <name>
        
    toggleblockson:
        aliases: [tbon]
        usage: /tbon <name>
        
    toggleblocksoff:
        aliases: [tboff]
        usage: /tboff <name>
                
    toggleblockslink:
        aliases: [tblink]
        usage: /tblink <name>
        
    toggleblocksrlink:
        aliases: [tbrlink]
        usage: /tbrlink <name>
        
    toggleblocksdelink:
        aliases: [tbdelink]
        usage: /tbdelink <name>
        
    toggleblockslist:
        aliases: [tblist]
        usage: /tblist
        
    toggleblocksdelete:
        aliases: [tbdelete, tbdel]
        usage: /tbdelete <name>
        
    toggleblocksinfo:
        aliases: [tbinfo]
        usage: /tbinfo
        
    toggleblocksselect:
        aliases: [tbselect, tbsel]
        usage: /tbselect <name>
        
    toggleblocksrename:
        aliases: [tbrename]
        usage: /tbrename <originalName> <newName>
        
    toggleblocksinclude:
        aliases: [tbinclude, tbinc]
        usage: /tbinclude <name>
        
    toggleblocksexclude:
        aliases: [tbexclude, tbexl]
        usage: /tbexclude <name>
        
    
    tbgroup:
        aliases: [tbg]
        usage: /tbgroup <name>
        
    tbgrouplist:
        aliases: [tbglist]
        usage: /tbglist
          
    tbgroupdelete:
        aliases: [tbgdelete, tbgdel]
        usage: /tbgdelete <group>
        
    tbgrouprename:
        aliases: [tbgrename]
        usage: /tbgrename <originalName> <newName>
        
    tbgroupinclude:
        aliases: [tbginclude, tbginc]
        usage: /tbginclude <area> <group>
        
    tbgroupexclude:
        aliases: [tbgexclude, tbgexl, tbgexc]
        usage: /tbgexclude <area> <group>
        
    tbgroupindex:
        aliases: [tbgindex]
        usage: /tbgindex <group> <index>
    
        
    toggleblockshelp:
        aliases: [tbhelp]
        usage: /tbhelp