name: Portals
main: portals.Portals
version: 1.0
commands:
    portal: 
        usage: /portal <name>
    portalto:
        usage: /portalto <name>
    portallist:
        usage: /portallist
    portaldelete:
        aliases: [portaldel]
        usage: /portaldelete <name>
    portalselect:
        aliases: [portalsel]
        usage: /portalselect <name>
    portalrename:
        usage: /portalrename <originalName> <newName>
