name: Portals
main: portals.Portals
version: 1.0
depend: [PuzzlePack]
commands:
    portal: 
        aliases: [po]
        usage: /po <name>
    portalto:
        aliases: [poto]
        usage: /poto <name>
    portallist:
        aliases: [polist]
        usage: /polist
    portaldelete:
        aliases: [portaldel, podelete, podel]
        usage: /podelete <name>
    portalselect:
        aliases: [portalsel, poselect, posel]
        usage: /poselect <name>
    portalrename:
        aliases: [porename]
        usage: /porename <originalName> <newName>
    portalhelp:
        aliases: [pohelp]
        usage: /pohelp
