name: BounceBlocks
main: bounceblocks.BounceBlocks
version: 1.0
depend: [PuzzlePack]
commands:
    bounceblock:
        aliases: [bblock, bb]
        usage: /bb <jumpStrength>
    
    bounceblockhelp:
        aliases: [bblockhelp, bbhelp]
        usage: /bbhelp