name: RedstoneCombiner
main: redstonecombiner.RedstoneCombiner
version: 1.0
depend: [PuzzlePack]
commands:
    
    redcombiner:
        aliases: [rc]
        usage: /rc <name>
    
    redcombinerlink:
        aliases: [rclink]
        usage: /rclink <name>
        
    redcombinerdelink:
        aliases: [rcdelink]
        usage: /rcdelink <name>
        
    redcombinerlist:
        aliases: [rclist]
        usage: /rclist
        
    redcombinerdelete:
        aliases: [rcdelete, rcdel]
        usage: /rcdelete <name>
        
    redcombinerrename:
        aliases: [rcrename]
        usage: /rcrename <originalName> <newName>
        
    redcombinerinfo:
        aliases: [rcinfo]
        usage: /rcinfo
        
    redcombinerhelp:
        aliases: [rchelp]
        usage: /rchelp
