name: RedstoneCombiner
main: redstonecombiner.RedstoneCombiner
version: 1.0
commands:
    
    redcombiner:
        aliases: [rc]
        usage: /redcombiner <name>
    
    redcombinerlink:
        aliases: [rclink]
        usage: /redcombinerlink <name>
        
    redcombinerdelink:
        aliases: [rcdelink]
        usage: /redcombinerdelink <name>
        
    redcombinerlist:
        aliases: [rclist]
        usage: /redcombinerlist
        
    redcombinerdelete:
        aliases: [rcdelete, rcdel]
        usage: /redcombinerdelete <name>
        
    redcombinerrename:
        aliases: [rcrename]
        usage: /redcombinerrename <originalName> <newName>
        
    redcombinerhelp:
        aliases: [rchelp]
        usage: /redcombinerhelp
