name: Telepads
main: telepads.Telepads
version: 1.0
depend: [PuzzlePack]
commands:
    telepad:
        aliases: [tpad]
        usage: /tpad <name>
        
    telepadfrom:
        aliases: [tpadfrom]
        usage: /tpadfrom <name>
        
    telepadto:
        aliases: [tpadto]
        usage: /tpadto <name>
        
    telepadlist:
        aliases: [tpadlist]
        usage: /tpadlist
        
    telepaddelete:
        aliases: [tpaddelete, tpaddel]
        usage: /tpaddelete <name>
        
    telepadhelp:
        aliases: [tpadhelp]
        usage: /tpadhelp