name: RestricedArea
main: restrictedarea.RestrictedArea
version: 1.0
commands: 
    ra:
        usage: /ra <name>
    
    rainclude:
        usage: /rainclude <name>
    
    raexclude:
        usage: /raexclude <name> [index]
    
    radelete:
        aliases: [radel]
        usage: /radelete <name>
        
    ralocation:
        usage: /ralocation <name>
        
    rarename:
        usage: /rarename <originalName> <newName>
        
    ralist:
        usage: /ralist
        
    raselect:
        aliases: [rasel]
        usage: /raselect <name> [index]
    
    raindex:
        usage: /raindex <name> <index>
    
    
    
    ragroup:
        aliases: [rag]
        usage: /ragroup <name>
        
    ragrouplist:
        aliases: [raglist]
        usage: /raglist
    
    ragroupadd:
        aliases: [ragadd]
        usage: /ragadd <area> <group>
        
    ragroupremove:
        aliases: [ragremove]
        usage: /ragremove <area> <group>
        
    ragroupdelete:
        aliases: [ragdelete]
        usage: /ragdelete <group>
    
    rahelp:
        usage: /rahelp
        