name: RestricedArea
main: restrictedarea.RestrictedArea
version: 1.0
commands: 
    ra:
        usage: /ra <name>
    
    rainclude:
        usage: /rainclude <name>
    
    raexclude:
        usage: /raexclude <name> [index]
    
    radelete:
        aliases: [radel]
        usage: /radelete <name>
        
    ralocation:
        usage: /ralocation <name>
        
    ramessage:
        usage: /ramessage <name> [message]
        
    rarename:
        usage: /rarename <originalName> <newName>
        
    ralist:
        usage: /ralist
        
    raselect:
        aliases: [rasel]
        usage: /raselect <name> [index]
    
    raindex:
        usage: /raindex <name> <index>
    
    
    
    ragroup:
        aliases: [rag]
        usage: /ragroup <name>
        
    ragrouplist:
        aliases: [raglist]
        usage: /raglist
          
    ragroupdelete:
        aliases: [ragdelete, ragdel]
        usage: /ragdelete <group>
        
    ragrouprename:
        aliases: [ragrename]
        usage: /ragrename <originalName> <newName>
        
    ragroupinclude:
        aliases: [raginclude, raginc]
        usage: /raginclude <area> <group>
        
    ragroupexclude:
        aliases: [ragexclude, ragexl, ragexc]
        usage: /ragexclude <area> <group>
        
    ragroupindex:
        aliases: [ragindex]
        usage: /ragindex <group> <index>
    
    rahelp:
        usage: /rahelp
        