name: AreaCollider
main: areacollider.AreaCollider
version: 1.0
depend: [PuzzlePack]
commands:
    area:
        aliases: [ac]
        usage: /ac <name> <sound> [message]
        
    areasecret:
        aliases: [areasec, acsecret, acsec]
        usage: /acsecret <name>
        
    areateleport:
        aliases: [areatel, acteleport, actel]
        usage: /acteleport <name> [message]

    arealist:
        aliases: [aclist]
        usage: /aclist
        
    areaselect:
        aliases: [areasel, acselect, acsel]
        usage: /acselect <name>
        
    areadelete:
        aliases: [areadel, acdelete, acdel]
        usage: /acdelete <name>
        
    areaclearinventory:
        aliases: [areacinv, accinv]
        usage: /accinv <name>
        
    arearename:
        aliases: [acrename]
        usage: /acrename <originalName> <newName>
        
    areahelp:
        aliases: [achelp]
        usage: /areahelp