name: AreaCollider
main: areacollider.AreaCollider
version: 1.0
depend: [PuzzlePack]
commands:
    areageneral:
        aliases: [acgeneral]
        usage: /acgeneral <name> <sound> <message>
        
    areasecret:
        aliases: [acsecret]
        usage: /acsecret <name>
        
    areateleport:
        aliases: [acteleport]
        usage: /acteleport <name> [message]
        
    areaclearinventory:
        aliases: [acclearinventory, accinv]
        usage: /acclearinventory <name>
        
    areamessage:
        aliases: [acmessage]
        usage: /acmessage <name> <message>
        
    areasound:
        aliases: [acsound]
        usage: /acsound <name> <sound>
        
    areabigmessage:
        aliases: [acbigmessage, acbmessage]
        usage: /acbigmessage <name>
        
    arealist:
        aliases: [aclist]
        usage: /aclist
        
    areaselect:
        aliases: [acselect, acsel]
        usage: /acselect <name>
        
    areadelete:
        aliases: [acdelete, acdel]
        usage: /acdelete <name>
        
    arearename:
        aliases: [acrename]
        usage: /acrename <originalName> <newName>
        
    areahelp:
        aliases: [achelp]
        usage: /areahelp