name: MinePillars
main: minepillars.MinePillars
version: 1.0;
commands: 
    minepillars:
        aliases: [mp]
        usage: /minepillars <length>
        
    minepillarshelp:
        aliases: [mphelp]
        usage: /minepillarshelp