name: MinePillars
main: minepillars.MinePillars
version: 1.0;
depend: [PuzzlePack]
commands: 
    minepillars:
        aliases: [mp]
        usage: /mp <length>
        
    minepillarshelp:
        aliases: [mphelp]
        usage: /mphelp